### ISSUE TITLE
[Feature Request] Some additions that I would like to see.

### ISSUE THREAD

**Issue by Caco-o-sapo** [purrplingcat/QuestFramework#13]
Here are some conditions that were likely good to be added.

- Hasmod: the name explain it self

Some neat additions:

- When using LostItem or the similar quest types the item that has to be delivered, has a different description to not be equal as normal items that are from the game.

**Comment by purrplingcat** [comment]
The second requirement is impossible to implement. QF doesn't change anything in items, it's out of scope for QF. Do this kind of things with JsonAssets or Content Patcher (like add your item which is used only for your quests with your needed description. Remember this item is only for use in LostItem quest).

The `HasMod` condition is implemented and will be available since version 1.1.0.
