### ISSUE TITLE
Non game-breaking red text bug in SMAPI

### ISSUE THREAD

**Issue by notwondering** [purrplingcat/QuestFramework#16]
Hi! I've only been using QF for about 3 days now-downloaded it for NPC Adventures when that started requiring it (July 27). Yesterday I started noticing little red bugs in SMAPI relating to QF-here's an example: https://smapi.io/log/8b99566378f6411485dc5962453f9343. After getting a little help in Discord, I am about to go through my custom NPC mods to see if one of them adds that particular dialogue string, but I don't think that's the only one I've seen-if I come across more I'll post the logs here. Any idea why those might be happening and if it might need fixing or is just a thing that happens sometimes? I don't notice anything happening in game, just see them in SMAPI if I happen to glance over there before closing the game out.

**Comment by purrplingcat** [comment]
Can you send me which dialogue line this causes and for which NPC? It looks like that dialogue contains sething in format ![.+] Which means quest name for add quest to questlog by speak with NPC (dialogue). QF parses weird string from this token.

**Comment by notwondering** [comment]
Still looking for it! It was just a guess that it might be an NPC, and I have... a lot of mods XD Wasn't in any of the ones I've checked so far (Minu, Mr. Ginger, Jasper, Mike, Muadhnait, Abandoned Bride, Jacob and Eloise from East Scarpe, Pickled Pete from WTD, Hekate and Hephaestus). About to broaden my search to expanded dialogue mods :-P

**Comment by notwondering** [comment]
FOUND IT!! It's in Morgan's dialogue strings, from SVE.

**Comment by purrplingcat** [comment]
If it's a dialogue sentence ends with exclamation and the adds some items, insert space between the exclamation mark and [ and your problem is solved by this workaround.

**Comment by notwondering** [comment]
Thank you! That's what it is. I'll try this searching process again for any new ones I find, then.

**Comment by Jonqora** [comment]
Here is how to fix the bug in QF source code:

(src/Patches/DialoguePatch.cs)
`string pattern = @"!\[(.+)\]";`

Right now this regex is not very specific. Two different problems with it. 
1. First, it will match things that are not QF quests if the dialogue has a ! followed by a [itemcode] or something.
2. Second, if there are two matching strings in the same dialogue entry, it will match them both together with everything inbetween.

Dialogue1: `"Hello farmer![74]"` this will match.
Dialogue2: `"Here's a quest for you... ![quest1@Jonqora.QFmod]$1#$e# And here's a second quest:![quest2@Jonqora.QFmod]$4"` this will match the whole thing as "`quest1@Jonqora.QFmod]$1#$e# And here's a second quest:![quest2@Jonqora.QFmod`" and it will break, QF will not add the quest(s).

Here is how to fix some of the problems
`string pattern = @"!\[([^\]]+?@[^\]]+?)\]";`

- using `[^\]` instead of `.` is better. `.` matches any character, but `[^\]` will not match `]` ... this way you don't end up overshooting and matching too much of a string that has multiple sets of brackets.
- adding `@` in the middle with characters on either side makes sure that you are only matching strings inside `![`...`]` if the string fits the general pattern of a QF quest.
- changing `+` to `+?` tells the regex matching to be "lazy" instead of "greedy"... it is another way to make sure that a match will not grab multiple different matches all in one.

If you make this change, here is now the dialogue will parse:
Dialogue1: `"Hello farmer![74]"` no more match, hooray!
Dialogue2: `"Here's a quest for you... ![quest1@Jonqora.QFmod]$1#$e# And here's a second quest:![quest2@Jonqora.QFmod]$4"` This will match with two group results: "`quest1@Jonqora.QFmod`" and "`quest2@Jonqora.QFmod`". 

You will need to change a bit more code if you decide you want QF to be able to add both results from same dialogue entry to quest log (right now it only adds a quest for `.Groups[1].Value`). But even if you don't change anything else, at least the first quest in the dialogue will work properly with the fixed regex.

**Comment by purrplingcat** [comment]
Thanks, nut there is a secondary effect. If you see the code, you know the quest parsing and adding is tricky and it's did in two phases:

1. Parse quest token with quesrt name by regex, find quest ID by the name and replace the name by id. All is before dialogue string is parsed.
2. Find the quest id in the string in parsed dialogue part and add that quest to questlog. Replaces the token with quest id with empty string.

This all because the character `@` in the quest name. This character is replaced in quest string with farmer's name and QF parse wrong name (from  `myQuest@PurrplingCat.TestQuest` dialogue parser makes `myQuestEllenPurrplingCat.TestQuest` and this quest with this name doesn't exist. And this is a big problem. I solved it with hack with two phase quest token parsing. It's tricky hack, but works. I know, this needs redesign and find better solution how to add quest from QF by dialogue with an NPC due to all as described in this comment and in this issue bug report.

**Comment by Jonqora** [comment]
Ooh, I see the problem. So the @ cannot be relied on to identify a quest, because the @ already gets replaced with player name in the parser. That is tricky!

(It is especially tricky because... especially if a player is using the item naming cheat, they might have a ] in their name and then the [^\]] check will not work either.)

I see that this is a more difficult problem than I thought. It *might* still be solvable with regex, but it would have to be a more complex expression for sure. I will think on it and see if I have any ideas.

**Comment by Jonqora** [comment]
Hmm. I wonder... could you just sub in what the @ is replaced by?

`string pattern = @"!\[([^\]]+?" + Game1.player.Name + "[^\]]+?)\]";`

**Comment by purrplingcat** [comment]
I can't remove `@` from quest names, because It's used on more places in the code for parsing name and ownerId and for add ownerId in APIs for work with quests like if you are worked in scope for your mod, you can write quest name without @ and QF adds @yourmodid after the name. I am thinking about not use [], but another paired chars which is not colliding with anything in SDV dialogues. It may be more safe.

**Comment by purrplingcat** [comment]
@Jonqora  Maybe use patter `[q <integer|string>]` and for the mod name in dialogue quests use `~~` as delimiter and replaces it with `@` when fetching quest? I hope the `~~` is not reserved. Or what do you suggest?

**Comment by notwondering** [comment]
Finally played through a day in game again and got another little error like the first: https://smapi.io/log/ca243d84aefe4bb999b8cbb512a41251 In process of figuring out where this one could have come from, will post here when I know.

**Comment by notwondering** [comment]
If I'm looking for [195] as what QF thinks might be a quest ID, this could be Jasper, SVE, or Charlie. If it's plain 195, well.... that's a lot more files it could be.

**Comment by purrplingcat** [comment]
It's the same.

**Comment by purrplingcat** [comment]
Solved with new pattern `[quest:<questName> <modId>` for custom quests and `[quest:<vanillaQuestId>` for vanilla SDV quests. Quests can be offered by talk with NPC without red alerts.
