### ISSUE TITLE
Repeatable quests once per season

### ISSUE THREAD

**Issue by LenneDalben** [purrplingcat/QuestFramework#3]
Hi, thank you for creating this framework! I'm working on a mod idea to add quests for cooked dishes that you can deliver to the NPC who requested it. Would it be possible to make quests repeatable? Specifically, repeatable in different seasons? To use your example of Abigail requesting the amethyst, would it would be possible to have the quest be offered in spring once per year, then in fall once per year, every year? This would help me not have to create the quest multiple times, and extend how long the player could still have the quests and complete them.
I did notice that if a quest was accepted but not completed, it'll show up again on the bulletin board, that's a great feature!

**Comment by purrplingcat** [comment]
Hi,

I can add some conditions like `AcceptedThisYear` and `NotAcceptedThisYear` which consumes the fullqualified quest name(s) or id(s) for check which quests will be assigned to the quest log in this game year. For define offer this quest only when this quest will be not assigned will work this example:

```js
{
"Offers": [
    {
      "QuestName": "abigail_amethyst",
      "OfferedBy": "Bulletinboard",
      "OfferDetails": {
        "NpcName": "Abigail", // Speak with Abigail to get this quest
        "DialogueText": "I have a craving for something special.#$b#@, can you bring me amethyst?"
      },
      "When": {
        "NotAssignedThisYear": "abigail_amethyst@purrplingcat.testquestmod",
        "Seasons": "spring fall"
      }
    },
  ]
}
```

The fullqualified quest name is requered because conditions are global and not work with quest context. I can try to implement support context for global conditions, but I am not sure if it's possible to implement it soon. 

For add this condition feature I must to implement this things (shorted list):

- Create quest stats object (json serializable)
- Add handlers for serialize quest stats to save file on game saving
- Add handlers to deserialize quest statsfrom save file on save game loaded
- Add handlers which checks the player's questlog was changed and some quest will be added or removed from the list (quest log is NetCode NetList. Currently I have not idea how work with it, i must to analyze it)
- Write condition handler for the (not)acceptedquest this year
- Expose conditions `AcceptedThisYear` and `NotAcceptedThisYear` using the "accepted this year" handler to common global condition list.

Due to my vacation from 9th July to 19th July I will look into that and try to implement when I come back. Please be patient.

Thanks for your feedback. I do my best to implement it when I will be back.

**Comment by LenneDalben** [comment]
Hi PurrplingCat, from the Discord chat, you mentioned it would be possible to implement condition KnownRecipe and NotKnownRecipe

**Comment by purrplingcat** [comment]
Added these new current season based conditions:

Condition | Example | Description
--- | --- | ---
QuestAcceptedThisYear    | `@self` or `abigail_amethyst` or `abigail_amethyst@purrplingcat.testquests` | Put magic `@self` or quest name or fullqualified quest name for check if this quest was accepted this year. non-fullqualified name or magic `@self` will be handled in current quest context.
QuestAcceptedThisSeason  | same as *QuestAcceptedThisYear* | Same as *QuestAcceptedThisYear* but for season.
QuestAcceptedThisDay     | same as *QuestAcceptedThisYear* | Same as *QuestAcceptedThisYear* but for day.
QuestAcceptedThisWeekDay | same as *QuestAcceptedThisYear* | Same as *QuestAcceptedThisYear* but for weekday.

All these conditions supports magic `@self` value which reffers current quests (by context) and non-fullqualified names of quests. QF detects fullqualified name automatically from current quest context.

Also all **global envirinment conditions** supports `not:` prefix for negate condition result. 
For example `not:QuestAcceptedThisYear` means specified quest was not accepted in this current year. Without the `not:` it means specified quest was accepted in this current year.

```js
"Offers": [
  {
    "QuestName": "abigail_amethyst",
    "OfferedBy": "NPC",
    "OfferDetails": {
      "NpcName": "Abigail", // Speak with Abigail to get this quest
      "DialogueText": "I have a craving for something special.#$b#@, can you bring me amethyst?"
    },
    "When": {
      "DaysOfWeek": "Monday Thursday Friday",
      "Seasons": "summer"
    }
  },
  {
    "QuestName": "bat_problem",
    "OfferedBy": "Mail",
    "OfferDetails": {
      "Topic": "The bat problem",
      "Text": "Hi, @,^Our town is not safe during nights, because agressive kind of bats attacking villagers and they are scared. Reduce the bat population and make this town safe again. Thanks ^   -Mayor Lewis"
    },
    "When": {
      "Weather": "cloudy"
      "not:QuestAcceptedThisYear": "@self"
    }
  },
  {
    "QuestName": "willy_fish_oil",
    "OfferedBy": "Bulletinboard",
    "When": {
      "DaysOfWeek": "Monday"
      "QuestAcceptedThisWeekDay": "@self"
    }
  }
]
```
